version: "2"
services:
  www:
    build: .
    ports:
      - "80:80"
    links:
      - db:db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kofradia_data
      MYSQL_USER: kofradia_www
      MYSQL_PASSWORD: passord
      MYSQL_ROOT_PASSWORD: passord
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - ./docker/config:/etc/mysql/conf.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_USER: kofradia_www
        MYSQL_PASSWORD: passord
        MYSQL_ROOT_PASSWORD: passord